management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
server:
  port: 8080
  servlet:
    context-path: /api/catalog
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml
  datasource:
    url: "jdbc:postgresql://localhost:5432/catalog?autoReconnect=true"
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      connection-test-query: select 1;
      minimum-idle: 5
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: public